spring.application.name=calm-painter
# HERE WE will have to add the Mongo Atlas Connection make use of ENV
# spring.mongodb.uri=mongodb+srv://USERNAME:PASSWORD@canerscluster.ya6cku4.mongodb.net/calmpainter?retryWrites=true&w=majority&appName=CanersCluster